steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/api/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/pricelens/pricelens-api:${_TAG}
      - .
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/pricelens/pricelens-api:${_TAG}
substitutions:
  _REGION: europe-west1
  _TAG: latest

